version = 0.1
[default.deploy.parameters]
stack_name = "foobarbizzbazz"
resolve_s3 = true
s3_prefix = "foobarbizzbazz"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=443971207211.dkr.ecr.us-east-1.amazonaws.com/foobarbizzbazz1f0e9d51/helloworldfunction19d43fc4repo"]
