AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ytwas ytdlp lambda function

Globals:
  Function:
    Timeout: 180

Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfterOneDay
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

  YtwasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          MY_S3_BUCKET: !Ref MyBucket
      Runtime: python3.11
      Handler: app.lambda_handler
      CodeUri: ./ytwas_function
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:PutObject"
                - "s3:PutObjectAcl"
              Resource:
                Fn::Sub: ${MyBucket.Arn}/*
      Events:
        Ytwas:
          Type: Api
          Properties:
            Path: /convert
            Method: post

Outputs:
  YtwasApi:
    Description: "API Gateway endpoint URL for Prod stage for ytwas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/convert/"
  YtwasFunction:
    Description: "Ytwas Lambda Function ARN"
    Value: !GetAtt YtwasFunction.Arn
  YtwasFunctionIamRole:
    Description: "Implicit IAM Role created for ytwas function"
    Value: !GetAtt YtwasFunctionRole.Arn
